### ISSUE TITLE
Meta: Issue of issues.

### ISSUE THREAD

**Issue by matthewhammer** [matthewhammer/motoko-example-20210805#3]
- [x] Demonstrate query calls that answer by assembling data from maps and relations in `State` module, like in CanCan.
see #4 
- [ ] Demonstrate access control basics.
- [ ] Demonstrate update calls that change data in one call.
- [ ] Demonstrate update calls that do transaction-like updates, with rollback.
- [ ] Demonstrate stable memory, and evolve toward current "best practices."

**Comment by nicolas-martin** [comment]
Hi @matthewhammer, love how clean this repo is compared to trying to parse through cancan. 

I'd love to know you'll do the stable memory part. I'm currently struggling with converting `RelShared` to `Rel` and vise versa. I thought it would be simply using the convenience function https://github.com/matthewhammer/motoko-example-20210805/blob/main/src/Rel.mo#L61

But I'm getting errors about implicit conversion.

**Comment by matthewhammer** [comment]
> But I'm getting errors about implicit conversion.

Could you give me more details?  Perhaps those errors surfaced with newer versions of the compiler than when I authored the code?

**Comment by nicolas-martin** [comment]
Shared defined as:
```swift
  public type StateShared = {
    tagDao : RelShared<Types.TagName, Types.DaoID>;
  };
```
State defined as:
```swift
  public type State = {
    access : Access.Access;

    // === Main entities ===
    daos : Map<Types.DaoID, Types.DAO>;

    // === Binary relations (relating entities) ===
    tagDao : Rel<Types.TagName, Types.DaoID>;
  };
```
```swift
  public func share(state : State) : StateShared {
    {
      tagdao = Rel.share(state.tagDao);
    }
  };
```
```
cannot implicitly instantiate function of type
  <X, Y>(Rel/2<X, Y>) -> RelShared/2<X, Y>
to argument of type
  Rel/3<TagName/1, DaoID/1>
because no instantiation of X/445, Y/287 makes
  Rel/3<TagName/1, DaoID/1>  <:  Rel/2<X/445, Y/287>
  ```

I also have another question. In cancan not all the states are copied into the SharedState struct, how come? Would they not want to preserve everything through upgrades?

**Comment by nicolas-martin** [comment]
Hi, any update on this? I love the relationship model but without stable upgrades we can't really use it. 

It probably boils down to my lack of knowledge as to how to instantiate Tries or something along those lines.
